### ISSUE TITLE
Get rid of buffer when opening gitpad

### ISSUE THREAD

**Issue by idelice** [yujinyuz/gitpad.nvim#7]
A new buffer is popping up along with gitpad:

<img width="202" alt="Screenshot 2024-05-15 at 00 00 11" src="https://github.com/yujinyuz/gitpad.nvim/assets/59118341/71f5410d-9cc5-4089-ad4f-5f43b83a1f72">

How can I disable that? The floating window is enough for me

**Comment by yujinyuz** [comment]
@idelice I'm not sure how to reproduce this.

Are you using a tabline plugin by any chance?

Like https://github.com/romgrk/barbar.nvim

**Comment by yujinyuz** [comment]
@idelice I just made a fix. Can you test and see if that fixes it for you?

**Comment by idelice** [comment]
Can confirm that I can close it when pressing `q` - thanks!
